//Şevval Bilğin 2221221013
package com.mycompany.sevval_bilgin_stock_personel_tracking;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class LogInFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogInFrame
     */
    public LogInFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_log_in = new javax.swing.JPanel();
        lbl_log_in_personel_number = new javax.swing.JLabel();
        lbl_log_in_personel_password = new javax.swing.JLabel();
        txt_log_in_personel_number = new javax.swing.JTextField();
        btn_log_in_log_in = new javax.swing.JButton();
        password_log_in_personel_password = new javax.swing.JPasswordField();
        lbl_log_in_log_in = new javax.swing.JLabel();
        btn_log_in_sign_in = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(345, 375));

        pnl_log_in.setBackground(new java.awt.Color(185, 231, 246));
        pnl_log_in.setMaximumSize(new java.awt.Dimension(345, 375));
        pnl_log_in.setMinimumSize(new java.awt.Dimension(345, 375));
        pnl_log_in.setPreferredSize(new java.awt.Dimension(345, 375));
        pnl_log_in.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_log_in_personel_number.setText("Personel Number");
        pnl_log_in.add(lbl_log_in_personel_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 40));

        lbl_log_in_personel_password.setText("Personel Password");
        pnl_log_in.add(lbl_log_in_personel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 110, 40));

        txt_log_in_personel_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_log_in_personel_numberActionPerformed(evt);
            }
        });
        pnl_log_in.add(txt_log_in_personel_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, 40));

        btn_log_in_log_in.setText("Log In");
        btn_log_in_log_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_in_log_inActionPerformed(evt);
            }
        });
        pnl_log_in.add(btn_log_in_log_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 40));
        pnl_log_in.add(password_log_in_personel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, 40));

        lbl_log_in_log_in.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        lbl_log_in_log_in.setText("LOG IN");
        pnl_log_in.add(lbl_log_in_log_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        btn_log_in_sign_in.setText("Sign In");
        btn_log_in_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_in_sign_inActionPerformed(evt);
            }
        });
        pnl_log_in.add(btn_log_in_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_log_in, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_log_in, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_log_in_personel_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_log_in_personel_numberActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_log_in_personel_numberActionPerformed

    private void btn_log_in_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_in_sign_inActionPerformed
        // TODO add your handling code here:
      
        this.dispose();
        SignInFrame signin = new SignInFrame();
        signin.setVisible(true);
    }//GEN-LAST:event_btn_log_in_sign_inActionPerformed

    private void btn_log_in_log_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_in_log_inActionPerformed
        // TODO add your handling code here:
        //Login metodundan dönen personel null değilse giriş yapar
        Personel pnew = Company_db.Login(Integer.parseInt(txt_log_in_personel_number.getText()), password_log_in_personel_password.getText());
        if (pnew.name != null) {
            if (pnew.position == Personel.Position.Leader) {
                //kullanıcı leadersa hangi sisteme girmek  istediği sorgulanır
                int option = JOptionPane.showConfirmDialog(rootPane,  "Do you want to go into Stock system "
                        + "or Personel system?\nYES option is for stock system\nNO option is for personel system ","question", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    this.setVisible(false);
                    StockViewUpdateFrame s1 = new StockViewUpdateFrame(pnew);
                    s1.setVisible(true);
                } else {
                    this.setVisible(false);
                    PersonelViewUpdateFrame p1 = new PersonelViewUpdateFrame(pnew);
                    p1.setVisible(true);
                }
            } else {
                //kullanıcı member ise direkt stok ekranına yönlendirilir
                this.setVisible(false);
                StockViewUpdateFrame s1 = new StockViewUpdateFrame(pnew);
                s1.setVisible(true);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Your password or personel number is wrong! plz check them");
        }
        
       

    }//GEN-LAST:event_btn_log_in_log_inActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_log_in_log_in;
    private javax.swing.JButton btn_log_in_sign_in;
    private javax.swing.JLabel lbl_log_in_log_in;
    private javax.swing.JLabel lbl_log_in_personel_number;
    private javax.swing.JLabel lbl_log_in_personel_password;
    private javax.swing.JPasswordField password_log_in_personel_password;
    private javax.swing.JPanel pnl_log_in;
    private javax.swing.JTextField txt_log_in_personel_number;
    // End of variables declaration//GEN-END:variables
}
