//Şevval Bilğin 2221221013
package com.mycompany.sevval_bilgin_stock_personel_tracking;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class UpdateInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateInfo
     */
    String s;
    Personel p;
   
int id;
    public UpdateInfoFrame(Personel p, String s) {
        this.s=s;
       id= Company_db.SearchByEmailFindId(p.email);
        initComponents();
        txt_update_info_email.setText(p.email);
        txt_update_info_name.setText(p.name);
        txt_update_info_surname.setText(p.surname);
        txt_update_info_personel_number.setText(Company_db.SearchByEmailFindId(p.email) + "");
        if (p.position == Personel.Position.Leader) {
            rbtn_leader.setSelected(true);
        } else {
            rbtn_member.setSelected(true);
        }
         String psw = p.password;
        
        

        password_update_info_personel_password.setText(psw);

        this.p = p;
    }
    public void UpdateInfos(){
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group_update_info_positions = new javax.swing.ButtonGroup();
        pnl_first = new javax.swing.JPanel();
        pnl_updateInfoFrame = new javax.swing.JPanel();
        lbl_update_info_surname = new javax.swing.JLabel();
        lbl_supdate_info_personel_number = new javax.swing.JLabel();
        lbl_update_info_personel_password = new javax.swing.JLabel();
        lbl_update_info_position = new javax.swing.JLabel();
        lbl_update_info_name = new javax.swing.JLabel();
        btn_update_info_update = new javax.swing.JButton();
        btn_update_info_cancel = new javax.swing.JButton();
        txt_update_info_name = new javax.swing.JTextField();
        txt_update_info_surname = new javax.swing.JTextField();
        txt_update_info_personel_number = new javax.swing.JTextField();
        lbl_sign_in_sign_in = new javax.swing.JLabel();
        password_update_info_personel_password = new javax.swing.JPasswordField();
        txt_update_info_email = new javax.swing.JTextField();
        lbl_update_info_email = new javax.swing.JLabel();
        rbtn_leader = new javax.swing.JRadioButton();
        rbtn_member = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_first.setBackground(new java.awt.Color(204, 255, 255));

        pnl_updateInfoFrame.setBackground(new java.awt.Color(150, 225, 197));
        pnl_updateInfoFrame.setMaximumSize(new java.awt.Dimension(377, 479));
        pnl_updateInfoFrame.setMinimumSize(new java.awt.Dimension(377, 479));

        lbl_update_info_surname.setText("Surname");

        lbl_supdate_info_personel_number.setText("Personel Number");

        lbl_update_info_personel_password.setText("Personel password");

        lbl_update_info_position.setText("Position");

        lbl_update_info_name.setText("Name");

        btn_update_info_update.setText("Update");
        btn_update_info_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_info_updateActionPerformed(evt);
            }
        });

        btn_update_info_cancel.setText("Cancel");
        btn_update_info_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_info_cancelActionPerformed(evt);
            }
        });

        txt_update_info_name.setEnabled(false);
        txt_update_info_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_update_info_nameActionPerformed(evt);
            }
        });

        txt_update_info_surname.setEnabled(false);

        txt_update_info_personel_number.setEnabled(false);
        txt_update_info_personel_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_update_info_personel_numberActionPerformed(evt);
            }
        });

        lbl_sign_in_sign_in.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        lbl_sign_in_sign_in.setText("UPDATE");

        lbl_update_info_email.setText("Email");

        btn_group_update_info_positions.add(rbtn_leader);
        rbtn_leader.setText("Leader");

        btn_group_update_info_positions.add(rbtn_member);
        rbtn_member.setText("Member");
        rbtn_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_memberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_updateInfoFrameLayout = new javax.swing.GroupLayout(pnl_updateInfoFrame);
        pnl_updateInfoFrame.setLayout(pnl_updateInfoFrameLayout);
        pnl_updateInfoFrameLayout.setHorizontalGroup(
            pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_sign_in_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbl_update_info_name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_update_info_name, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbl_update_info_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_update_info_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbl_update_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_update_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbl_supdate_info_personel_number, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_update_info_personel_number, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_update_info_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btn_update_info_update, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_update_info_personel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_update_info_position, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_leader, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_member, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(password_update_info_personel_password)
                                .addGap(38, 38, 38)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnl_updateInfoFrameLayout.setVerticalGroup(
            pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_sign_in_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_update_info_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_update_info_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_update_info_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_update_info_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_update_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_update_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_supdate_info_personel_number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_update_info_personel_number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_update_info_personel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_updateInfoFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password_update_info_personel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(pnl_updateInfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_update_info_position, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtn_leader)
                    .addComponent(rbtn_member))
                .addGap(49, 49, 49)
                .addComponent(btn_update_info_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_update_info_cancel)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_firstLayout = new javax.swing.GroupLayout(pnl_first);
        pnl_first.setLayout(pnl_firstLayout);
        pnl_firstLayout.setHorizontalGroup(
            pnl_firstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_firstLayout.createSequentialGroup()
                .addComponent(pnl_updateInfoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_firstLayout.setVerticalGroup(
            pnl_firstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_firstLayout.createSequentialGroup()
                .addComponent(pnl_updateInfoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_update_info_personel_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_update_info_personel_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_update_info_personel_numberActionPerformed

    private void txt_update_info_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_update_info_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_update_info_nameActionPerformed

    private void btn_update_info_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_info_cancelActionPerformed
        // TODO add your handling code here:
     //önceki sayfaya geri döner
        if (s.compareToIgnoreCase("s") == 0) {
            StockViewUpdateFrame s1 = new StockViewUpdateFrame(p);
            s1.setVisible(true);
        } else  {
            PersonelViewUpdateFrame p1 = new PersonelViewUpdateFrame(p);
            p1.setVisible(true);
        }  this.setVisible(false);
    }//GEN-LAST:event_btn_update_info_cancelActionPerformed

    private void btn_update_info_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_info_updateActionPerformed
        // TODO add your handling code here:
        Personel newp = new Personel();

        //yeni bilgilerin önceki kurallara uyup uymadığını kontrol eder.
//        örn-> maillerin sonunun @gmail.com)ya da @hotmail.com ile bitmesi
        Pattern pattern = Pattern.compile("^(([a-z&&A-Z]||[1-9]){1,})(((@gmail.com)|@hotmail.com))$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(txt_update_info_email.getText());
        boolean matchFound = matcher.find();
        boolean isAddedDB = false;
        if (matchFound) {
            if (rbtn_member.isSelected()) {
                isAddedDB = Company_db.SearchbyIdFindPersonelAndUpdate(id, txt_update_info_email.getText(),
                        password_update_info_personel_password.getText(), "Member");

            } else {
                isAddedDB = Company_db.SearchbyIdFindPersonelAndUpdate(id, txt_update_info_email.getText(),
                        password_update_info_personel_password.getText(), "Leader");
            }
            if (isAddedDB) {
                
                newp.email = txt_update_info_email.getText();
                newp.name = txt_update_info_name.getText();
                newp.surname = txt_update_info_surname.getText();
                newp.password = password_update_info_personel_password.getText();
                if (rbtn_member.isSelected()) {
                    newp.position = Personel.Position.Member;
                }JOptionPane.showMessageDialog(rootPane, "User Updated!!");
                 if (s.compareToIgnoreCase("s") == 0) {
            StockViewUpdateFrame s1 = new StockViewUpdateFrame(p);
            s1.setVisible(true);
        } else  {
            PersonelViewUpdateFrame p1 = new PersonelViewUpdateFrame(p);
            p1.setVisible(true);
        }  this.setVisible(false);
                
               
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Your email should end with \n @gmail.com or @hotmail.com");
        }

    }//GEN-LAST:event_btn_update_info_updateActionPerformed

    private void rbtn_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_memberActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_group_update_info_positions;
    private javax.swing.JButton btn_update_info_cancel;
    private javax.swing.JButton btn_update_info_update;
    private javax.swing.JLabel lbl_sign_in_sign_in;
    private javax.swing.JLabel lbl_supdate_info_personel_number;
    private javax.swing.JLabel lbl_update_info_email;
    private javax.swing.JLabel lbl_update_info_name;
    private javax.swing.JLabel lbl_update_info_personel_password;
    private javax.swing.JLabel lbl_update_info_position;
    private javax.swing.JLabel lbl_update_info_surname;
    private javax.swing.JPasswordField password_update_info_personel_password;
    private javax.swing.JPanel pnl_first;
    private javax.swing.JPanel pnl_updateInfoFrame;
    private javax.swing.JRadioButton rbtn_leader;
    private javax.swing.JRadioButton rbtn_member;
    private javax.swing.JTextField txt_update_info_email;
    private javax.swing.JTextField txt_update_info_name;
    private javax.swing.JTextField txt_update_info_personel_number;
    private javax.swing.JTextField txt_update_info_surname;
    // End of variables declaration//GEN-END:variables
}
