//Şevval Bilğin 2221221013
package com.mycompany.sevval_bilgin_stock_personel_tracking;

import static com.mycompany.sevval_bilgin_stock_personel_tracking.Company_db.connectionString;
import java.awt.Color;
import java.awt.Font;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class PersonelViewUpdateFrame extends javax.swing.JFrame {

    /**
     * Creates new form PersonelViewUpdate
     */
    public static Personel pnew = new Personel();
    public static Personel pnew2 = new Personel();
    private DefaultTableModel lis = new DefaultTableModel();

    public PersonelViewUpdateFrame(Personel p) {
        initComponents();

        GetAllUsersFromDatabase();
        int id;
        pnew = p;
        pnew2 = p;

//        
    }

    public void GetAllUsersFromDatabase() {
        try {

            Company_db.conn = DriverManager.getConnection(connectionString);
            Statement stmt = Company_db.conn.createStatement();
            String query = "SELECT * FROM stock_company_personels.personel;";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {

                Personel p = new Personel();
                p.email = rs.getString("email");
                p.name = rs.getString("name");
                p.surname = rs.getString("surname");
                p.password = rs.getString("password");

                if (rs.getString("position").compareTo("Member") == 0) {
                    p.position = Personel.Position.Member;
                    String DBdata[] = {Company_db.SearchByEmailFindId(p.email) + "", p.name, p.surname, p.password, "Member", p.email};
                    lis = (DefaultTableModel) table_personel.getModel();
                    lis.addRow(DBdata);
                }
                if (rs.getString("position").compareTo("Leader") == 0) {
                    p.position = Personel.Position.Leader;
                    String DBdata[] = {Company_db.SearchByEmailFindId(p.email) + "", p.name, p.surname, p.password, "Leader", p.email};
                    lis = (DefaultTableModel) table_personel.getModel();
                    lis.addRow(DBdata);

                }

            }

            Company_db.conn.close();
        } catch (SQLException ex) {

            Logger.getLogger(Company_db.class.getName()).log(Level.SEVERE, null, ex);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        pnl_personel_view_update = new javax.swing.JPanel();
        txt_personel_Search = new javax.swing.JTextField();
        btn_personel_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_personel = new javax.swing.JTable();
        pnl_personel_buttons = new javax.swing.JPanel();
        btn_personel_add = new javax.swing.JButton();
        btn_personel_cancel = new javax.swing.JButton();
        btn_personel_update = new javax.swing.JButton();
        btn_delete_personel = new javax.swing.JButton();
        btn_update_personel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        radiobtn_menu_personel_reading = new javax.swing.JRadioButtonMenuItem();
        checkbox_menu_personel_serif = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_personel_view_update.setBackground(new java.awt.Color(204, 204, 204));
        pnl_personel_view_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_personel_view_updateMouseClicked(evt);
            }
        });
        pnl_personel_view_update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl_personel_view_update.add(txt_personel_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 40));

        btn_personel_search.setText("SEARCH");
        btn_personel_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personel_searchActionPerformed(evt);
            }
        });
        pnl_personel_view_update.add(btn_personel_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 150, 40));

        table_personel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "SURNAME", "PASSWORD", "POSİTİON", "EMAİL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_personel);
        if (table_personel.getColumnModel().getColumnCount() > 0) {
            table_personel.getColumnModel().getColumn(0).setResizable(false);
            table_personel.getColumnModel().getColumn(1).setResizable(false);
            table_personel.getColumnModel().getColumn(2).setResizable(false);
            table_personel.getColumnModel().getColumn(3).setResizable(false);
            table_personel.getColumnModel().getColumn(4).setResizable(false);
            table_personel.getColumnModel().getColumn(5).setResizable(false);
        }

        pnl_personel_view_update.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 520, 480));

        pnl_personel_buttons.setBackground(new java.awt.Color(0, 102, 102));

        btn_personel_add.setText("ADD PERSONEL");
        btn_personel_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personel_addActionPerformed(evt);
            }
        });

        btn_personel_cancel.setText("CANCEL TO LOGIN PAGE");
        btn_personel_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personel_cancelActionPerformed(evt);
            }
        });

        btn_personel_update.setText("UPDATE YOUR PROFİLE");
        btn_personel_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personel_updateActionPerformed(evt);
            }
        });

        btn_delete_personel.setText("DELETE PERSONEL");
        btn_delete_personel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_personelActionPerformed(evt);
            }
        });

        btn_update_personel.setText("UPDATE PERSONEL");
        btn_update_personel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_personelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_personel_buttonsLayout = new javax.swing.GroupLayout(pnl_personel_buttons);
        pnl_personel_buttons.setLayout(pnl_personel_buttonsLayout);
        pnl_personel_buttonsLayout.setHorizontalGroup(
            pnl_personel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_personel_buttonsLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(pnl_personel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_update_personel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete_personel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_personel_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_personel_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_personel_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        pnl_personel_buttonsLayout.setVerticalGroup(
            pnl_personel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personel_buttonsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_personel_add, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_delete_personel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_update_personel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_personel_update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_personel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        jMenu1.setText("MODES");

        radiobtn_menu_personel_reading.setText("Reading mode");
        radiobtn_menu_personel_reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_menu_personel_readingActionPerformed(evt);
            }
        });
        jMenu1.add(radiobtn_menu_personel_reading);

        checkbox_menu_personel_serif.setText("Seris font Mode");
        checkbox_menu_personel_serif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_menu_personel_serifActionPerformed(evt);
            }
        });
        jMenu1.add(checkbox_menu_personel_serif);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_personel_view_update, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_personel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_personel_view_update, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
            .addComponent(pnl_personel_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static int id;
    public static String[] s;

    private void btn_personel_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personel_searchActionPerformed
        // TODO add your handling code here:
        //search işlemini yaparkene önce tabloyu sıfırladım

        int a = table_personel.getRowCount();
        lis = (DefaultTableModel) table_personel.getModel();
        lis.setRowCount(0);

        for (int i = 0; i < a; i++) {
            if (lis.getRowCount() != 0) {
                lis.removeRow(a - i);
            }
        }

        //search yapııp tabloya yazdım
        ArrayList<Personel> spersonels = Company_db.SearchByNameOrSurnameOrEmailOrPosition(txt_personel_Search.getText());

        for (Personel p : spersonels) {

            id = Company_db.SearchByEmailFindId(p.email);
            s = new String[6];
            s[0] = id + "";
            s[1] = p.name;
            s[2] = p.surname;
            s[3] = p.password;
            if (Personel.Position.Leader == p.position) {
                s[4] = "Leader";
            } else {
                s[4] = "Member";
            }
            s[5] = p.email;
            lis.addRow(s);

        }


    }//GEN-LAST:event_btn_personel_searchActionPerformed

    private void checkbox_menu_personel_serifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_menu_personel_serifActionPerformed
        // TODO add your handling code here:
        if (checkbox_menu_personel_serif.isSelected()) {
            txt_personel_Search.setFont(new Font("Serif", Font.PLAIN, 14));
            btn_personel_search.setFont(new Font("Serif", Font.PLAIN, 14));
            btn_personel_add.setFont(new Font("Serif", Font.PLAIN, 14));
            btn_personel_cancel.setFont(new Font("Serif", Font.PLAIN, 14));
            btn_personel_update.setFont(new Font("Serif", Font.PLAIN, 14));
        } else {
            txt_personel_Search.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            btn_personel_search.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            btn_personel_add.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            btn_personel_cancel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
            btn_personel_update.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        }

    }//GEN-LAST:event_checkbox_menu_personel_serifActionPerformed

    private void radiobtn_menu_personel_readingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_menu_personel_readingActionPerformed
        // TODO add your handling code here:

        if (radiobtn_menu_personel_reading.isSelected()) {
            pnl_personel_view_update.setBackground(Color.black);
        } else {
            pnl_personel_view_update.setBackground(Color.gray);
        }
    }//GEN-LAST:event_radiobtn_menu_personel_readingActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_personel_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personel_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LogInFrame l = new LogInFrame();
        l.setVisible(true);
    }//GEN-LAST:event_btn_personel_cancelActionPerformed

    private void btn_personel_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personel_updateActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        UpdateInfoFrame f1 = new UpdateInfoFrame(pnew2, "p");
        f1.setVisible(true);

    }//GEN-LAST:event_btn_personel_updateActionPerformed

    private void btn_personel_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personel_addActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SignInFrame s1 = new SignInFrame(pnew, this);
        s1.setVisible(true);
    }//GEN-LAST:event_btn_personel_addActionPerformed

    private void pnl_personel_view_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_personel_view_updateMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_pnl_personel_view_updateMouseClicked

    private void btn_update_personelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_personelActionPerformed
        // TODO add your handling code here:
        //se.ili bir kişi varsa onun bilgilerini update eder
        if (table_personel.getSelectedRow() != -1) {
            int indx = table_personel.getSelectedRow();
            Personel pupdate = new Personel();

            pupdate.name = (String) lis.getValueAt(table_personel.getSelectedRow(), 1);
            pupdate.surname = (String) lis.getValueAt(table_personel.getSelectedRow(), 2);
            pupdate.password = (String) lis.getValueAt(table_personel.getSelectedRow(), 3);
            if (((String) lis.getValueAt(table_personel.getSelectedRow(), 4)).compareTo("Leader") == 0) {
                pupdate.position = Personel.Position.Leader;
            } else {
                pupdate.position = Personel.Position.Member;
            }
            pupdate.email = (String) lis.getValueAt(table_personel.getSelectedRow(), 5);
            UpdateInfoFrame u = new UpdateInfoFrame(pupdate, "p");
            this.setVisible(false);
            u.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Personel NOT SELECTED!!");
        }
    }//GEN-LAST:event_btn_update_personelActionPerformed

    private void btn_delete_personelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_personelActionPerformed
        // TODO add your handling code here:
        //seçilen satırdaki personeli önce databaseden sonra tablodan siler
        int[] rows = table_personel.getSelectedRows();
        for (int row : rows) {
            boolean isDeleted = Company_db.DeletePersonel((Integer.parseInt(lis.getValueAt(row, 0).toString())));
            if (isDeleted) {
                lis.removeRow(row);
                JOptionPane.showMessageDialog(rootPane, "Personel Deleted!!");
            }
        }
    }//GEN-LAST:event_btn_delete_personelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete_personel;
    private javax.swing.JButton btn_personel_add;
    private javax.swing.JButton btn_personel_cancel;
    private javax.swing.JButton btn_personel_search;
    private javax.swing.JButton btn_personel_update;
    private javax.swing.JButton btn_update_personel;
    private javax.swing.JCheckBoxMenuItem checkbox_menu_personel_serif;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_personel_buttons;
    private javax.swing.JPanel pnl_personel_view_update;
    private javax.swing.JRadioButtonMenuItem radiobtn_menu_personel_reading;
    private javax.swing.JTable table_personel;
    private javax.swing.JTextField txt_personel_Search;
    // End of variables declaration//GEN-END:variables
}
