//Şevval Bilğin 2221221013
package com.mycompany.sevval_bilgin_stock_personel_tracking;

import java.awt.Frame;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SignInFrame extends javax.swing.JFrame {

    Frame parentfr;

    /**
     * Creates new form SİgnInFrame
     */
    public SignInFrame() {
        initComponents();
    }
    //kullanıcı bilgilerini bir kullanıcı kendi de düzenleyebilir ,
//    bir leader da düzenleyebilir bu sebeple giriş yapan kjullanıcıyı tuttum
    Personel myself;

    public SignInFrame(Personel myself, Frame p) {
        initComponents();
        parentfr = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sign_in = new javax.swing.JPanel();
        cmbx_sign_in_position = new javax.swing.JComboBox<>();
        lbl_sign_in_surname = new javax.swing.JLabel();
        lbl_sign_in_personel_number = new javax.swing.JLabel();
        lbl_sign_in_personel_password = new javax.swing.JLabel();
        lbl_sign_in_position = new javax.swing.JLabel();
        lbl_sign_in_name = new javax.swing.JLabel();
        btn_sign_in_sign_in = new javax.swing.JButton();
        btn_sign_in_cancel = new javax.swing.JButton();
        txt_sign_in_name = new javax.swing.JTextField();
        txt_sign_in_surname = new javax.swing.JTextField();
        txt_sign_in_personel_number = new javax.swing.JTextField();
        lbl_sign_in_sign_in = new javax.swing.JLabel();
        password_sign_in_personel_password = new javax.swing.JPasswordField();
        txt_sign_in_email = new javax.swing.JTextField();
        lbl_sign_in_email = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_sign_in.setBackground(new java.awt.Color(150, 225, 197));
        pnl_sign_in.setMaximumSize(new java.awt.Dimension(377, 479));
        pnl_sign_in.setMinimumSize(new java.awt.Dimension(377, 479));
        pnl_sign_in.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbx_sign_in_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Team Leader", "Team Member" }));
        pnl_sign_in.add(cmbx_sign_in_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 140, 40));

        lbl_sign_in_surname.setText("Surname");
        pnl_sign_in.add(lbl_sign_in_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 30));

        lbl_sign_in_personel_number.setText("Personel Number");
        pnl_sign_in.add(lbl_sign_in_personel_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 30));

        lbl_sign_in_personel_password.setText("Personel password");
        pnl_sign_in.add(lbl_sign_in_personel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 100, 30));

        lbl_sign_in_position.setText("Position");
        pnl_sign_in.add(lbl_sign_in_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 30));

        lbl_sign_in_name.setText("Name");
        pnl_sign_in.add(lbl_sign_in_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 30));

        btn_sign_in_sign_in.setText("Sign In");
        btn_sign_in_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_in_sign_inActionPerformed(evt);
            }
        });
        pnl_sign_in.add(btn_sign_in_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 90, 40));

        btn_sign_in_cancel.setText("Cancel");
        btn_sign_in_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_in_cancelActionPerformed(evt);
            }
        });
        pnl_sign_in.add(btn_sign_in_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 90, -1));

        txt_sign_in_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sign_in_nameActionPerformed(evt);
            }
        });
        pnl_sign_in.add(txt_sign_in_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 40));
        pnl_sign_in.add(txt_sign_in_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, 40));

        txt_sign_in_personel_number.setEnabled(false);
        txt_sign_in_personel_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sign_in_personel_numberActionPerformed(evt);
            }
        });
        pnl_sign_in.add(txt_sign_in_personel_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 140, 40));

        lbl_sign_in_sign_in.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        lbl_sign_in_sign_in.setText("SIGN IN");
        pnl_sign_in.add(lbl_sign_in_sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, 50));
        pnl_sign_in.add(password_sign_in_personel_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 140, 40));
        pnl_sign_in.add(txt_sign_in_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 140, 40));

        lbl_sign_in_email.setText("Email");
        pnl_sign_in.add(lbl_sign_in_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_sign_in, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_sign_in, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sign_in_personel_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sign_in_personel_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sign_in_personel_numberActionPerformed

    private void txt_sign_in_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sign_in_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sign_in_nameActionPerformed

    private void btn_sign_in_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign_in_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if (parentfr == null) {
            LogInFrame login = new LogInFrame();
            login.setVisible(true);
        } else {
            PersonelViewUpdateFrame p = new PersonelViewUpdateFrame(myself);
            p.setVisible(true);
        }
    }//GEN-LAST:event_btn_sign_in_cancelActionPerformed

    private void btn_sign_in_sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign_in_sign_inActionPerformed
        // TODO add your handling code here:
        Personel newp = new Personel();
        boolean isAdded = false;
        //mailin sonu @gmail.com)ya da @hotmail.com ile bitmeli
        Pattern pattern = Pattern.compile("^(([a-z&&A-Z]||[1-9]){1,})(((@gmail.com)|@hotmail.com))$", Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(txt_sign_in_email.getText());
        boolean matchFound = matcher.find();
        if (txt_sign_in_email == null || txt_sign_in_name == null || txt_sign_in_surname == null || password_sign_in_personel_password == null) {
            JOptionPane.showMessageDialog(rootPane, "You should fill in all fields!!");
        }
        //kayıt başarılıysa yeni bir personel oluşturulur
        if (matchFound) {
            try {

                newp.email = txt_sign_in_email.getText();
                newp.name = txt_sign_in_name.getText();
                newp.surname = txt_sign_in_surname.getText();
                newp.password = password_sign_in_personel_password.getText();
                if (cmbx_sign_in_position.getSelectedIndex() == 0) {
                    newp.position = Personel.Position.Leader;
                } else {
                    newp.position = Personel.Position.Member;
                }
                boolean isAddedDB = Company_db.AddPersonel(newp);
                if (isAddedDB) {
                    JOptionPane.showMessageDialog(rootPane, "Personel Added!YOUR PERSONEL NUMBER IS " + Company_db.SearchByEmailFindId(newp.email));
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Email is used by another personel.Plz use anothwer email address!!");
                }
                this.dispose();
                if (parentfr == null) {
                    LogInFrame login = new LogInFrame();
                    login.setVisible(true);
                } else {
                    PersonelViewUpdateFrame p = new PersonelViewUpdateFrame(myself);
                    p.setVisible(true);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignInFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(SignInFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(SignInFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Your email should end with @gmail.com or @hotmail.com");
        }
        txt_sign_in_email.setText("");

    }//GEN-LAST:event_btn_sign_in_sign_inActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sign_in_cancel;
    private javax.swing.JButton btn_sign_in_sign_in;
    private javax.swing.JComboBox<String> cmbx_sign_in_position;
    private javax.swing.JLabel lbl_sign_in_email;
    private javax.swing.JLabel lbl_sign_in_name;
    private javax.swing.JLabel lbl_sign_in_personel_number;
    private javax.swing.JLabel lbl_sign_in_personel_password;
    private javax.swing.JLabel lbl_sign_in_position;
    private javax.swing.JLabel lbl_sign_in_sign_in;
    private javax.swing.JLabel lbl_sign_in_surname;
    private javax.swing.JPasswordField password_sign_in_personel_password;
    private javax.swing.JPanel pnl_sign_in;
    private javax.swing.JTextField txt_sign_in_email;
    private javax.swing.JTextField txt_sign_in_name;
    private javax.swing.JTextField txt_sign_in_personel_number;
    private javax.swing.JTextField txt_sign_in_surname;
    // End of variables declaration//GEN-END:variables
}
